apiVersion: v1
kind: Service
metadata:
  name: devops-rest-service
spec:
  selector:
    app: devops-rest
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: {{ .Values.service.type }}