version: '3.7'
services:
  db:
    image: mysql:8.0.33
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # My OLD Mac MySQL client only support native passwords
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${db_user}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${db_user}
      # You can use whatever password you like
      MYSQL_PASSWORD: /run/secrets/db_password
      # Password for root access
      MYSQL_ROOT_PASSWORD: /run/secrets/root_db_password
    secrets:
      - db_password
      - root_db_password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  rest:
    build: .
    container_name: devops-rest
    image: devops-rest:${IMAGE_TAG}
    depends_on:
      db:
        condition: service_healthy
    environment:
        db_host: ${db_host}
        db_port: ${db_port}
        db_user: ${db_user}
        db_pass: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5000:5000"
    # Healthcheck to check server is up
    # see healthcheck output using - docker inspect --format "{{json .State.Health }}" <container name>
    healthcheck:
      test: curl --fail http://localhost:5000/users/1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
secrets:
  db_password:
    file: ./db_password.txt
  root_db_password:
    file: ./root_db_password.txt
# Names our volume
volumes:
  my-db:
    name: devops-db-data